server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: ledger-service
  profiles:
    default: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
