server:
  port: ${PORT:0}

spring:
  application:
    name: ${APP_NAME:app}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
