server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: ledger-service
  profiles:
    default: local
  datasource:
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info
