server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/auth/**,/merchant/auth/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/payments/**
        - id: swagger-ui
          uri: http://localhost:8083
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedorigins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
            allowedmethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedheaders:
              - "*"
            allowcredentials: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:payflow}

app:
  jwt:
    secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}