# Local Development Profile

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: payflow

payflow:
  redis:
    enabled: true

security:
  jwt:
    secret-key: cGF5Zmxvdy1kZXYtanR0LXNlY3JldC1rZXktMjU2Yml0cy1taW5pbXVtLWZvci1zZWN1cml0eQ==

application:
  jwt:
    secret: cGF5Zmxvdy1kZXYtanR0LXNlY3JldC1rZXktMjU2Yml0cy1taW5pbXVtLWZvci1zZWN1cml0eQ==
    expiration: 86400000

logging:
  level:
    root: INFO
    dev.payment.apigateway: DEBUG