spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/payflow
    username: payflow
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

app:
  auth-service:
    url: http://auth-service:8082
  simulator:
    url: http://simulator-service:8086
  notification:
    url: http://notification-service:8085
  webhook:
    secret: ${PAYMENT_WEBHOOK_SECRET}
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET}
  merchant:
    api-keys: ${MERCHANT_API_KEYS}

server:
  port: 8083