spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/payflow
    username: payflow
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

app:
  auth-service:
    url: http://auth-service:8082
  simulator:
    url: http://simulator-service:8086
  notification:
    url: http://notification-service:8085
  webhook:
    secret: ${PAYMENT_WEBHOOK_SECRET}
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET}
  merchant:
    api-keys: ${MERCHANT_API_KEYS}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true