server:
  port: 8086

payflow:
  redis:
    enabled: false

spring:
  application:
    name: simulator-service
  profiles:
    active: docker

simulator:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
