services:
  api-gateway:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
      simulator-service:
        condition: service_started
      analytics-service:
        condition: service_started
      audit-service:
        condition: service_started
      zipkin:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: hybrid
      AUTH_SERVICE_URL: http://host.docker.internal:8081
      ORDER_SERVICE_URL: http://host.docker.internal:8082

  payment-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      simulator-service:
        condition: service_started
      notification-service:
        condition: service_started
      zipkin:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: hybrid
      AUTH_SERVICE_URL: http://host.docker.internal:8081
      ORDER_SERVICE_URL: http://host.docker.internal:8082

  order-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  auth-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  notification-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  simulator-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  analytics-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  audit-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: hybrid

  sonarqube:
    image: sonarqube:9.9.4-community
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - payflow-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000/api/system/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s

networks:
  payflow-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
