server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments
  jpa:
    hibernate:
      ddl-auto: validate   # trust Flyway for schema
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
