server:
  port: 8086

webhook:
  service-url: ${WEBHOOK_SERVICE_URL:http://localhost:8085}
  simulator-success-rate: ${SIMULATOR_SUCCESS_RATE:90}
  simulator-mode: ${SIMULATOR_MODE:random}

spring:
  application:
    name: simulator-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/paymentdb}
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
