spring:
  datasource:
    url: ${SIMULATOR_DB_URL:jdbc:postgresql://localhost:5433/simulatordb}
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
  jpa:
    hibernate:
      ddl-auto: update
