server:
  port: 8086
  shutdown: graceful

spring:
  application:
    name: simulator-service
  datasource:
    url: jdbc:postgresql://postgres:5432/simulator_db
    username: payflow
    password: payflow
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 25000
      pool-name: SimulatorHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  flyway:
    enabled: false

webhook:
  service-url: http://notification-service:8084
  simulator-success-rate: 90
  simulator-mode: random

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
