server:
  port: ${SERVER_PORT:8086}
spring:
  application:
    name: settlement-service
  datasource:
    url: ${SETTLEMENT_DB_URL:jdbc:postgresql://localhost:5432/paymentdb?currentSchema=settlement_core}
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    create-schemas: true
    schemas: settlement_core
    default-schema: settlement_core

management:
  endpoints:
    web:
      exposure:
        include: health,info
