server:
  port: 8086

spring:
  application:
    name: settlement-service

  datasource:
    url: jdbc:postgresql://postgres:5432/settlementdb
    username: payment
    password: paymentpass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO