server:
  port: ${PORT:0}
spring:
  application:
    name: ${APP_NAME:settlement-service}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  profiles:
    default: local
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
