server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/payflow_auth
    username: payflow
    password: payflow
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 25000
      pool-name: AuthHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
          time_zone: UTC
        type:
          deprecated_uuid_char_type: true
  flyway:
    enabled: false
  data:
    redis:
      host: redis
      port: 6379
      password: payflow-redis

application:
  jwt:
    secret: dGhpcy1pcy1hLXZlcnktc2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1maW50ZWNoLXBheW1lbnQta2V5LWJhc2U2NC1lbmNvZGVk
    expiration: 86400000
    refresh-expiration: 604800000

resilience4j:
  ratelimiter:
    instances:
      login:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 10s
        register-health-indicator: true
        event-consumer-buffer-size: 100
      register:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 30s
        register-health-indicator: true
      refresh:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 5s
        register-health-indicator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    dev.payment.authservice: DEBUG