spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: payment
    password: paymentpass

  jpa:
    hibernate:
      ddl-auto: validate