server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_analytics
    username: ${DB_USERNAME:payflow}
    password: ${DB_PASSWORD:payflow}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:payflow-redis}
  kafka:
    bootstrap-servers: localhost:9092

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:dev-only-jwt-secret-minimum-32-chars-required}

logging:
  level:
    root: INFO
    dev.payment.analyticsservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always