spring:
  config:
    import: vault://secret/analytics-service

vault:
  enabled: true
  token: ${VAULT_TOKEN:}

datasource:
  password: ${DB_PASSWORD:${vault:db-password:}}

logging:
  level:
    root: INFO
    dev.payment: INFO
