CREATE TABLE templates
(
    id UUID PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL UNIQUE,
    channel VARCHAR(32) NOT NULL,
    subject VARCHAR(120) NOT NULL,
    body VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications
(
    id UUID PRIMARY KEY,
    recipient_address VARCHAR(255) NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
