receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"
processors:
  batch: {}
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
