spring:
  datasource:
    url: ${RISK_DB_URL:jdbc:postgresql://postgres:5432/riskdb}
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
  jpa:
    hibernate:
      ddl-auto: update
