server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payflow}
    username: ${POSTGRES_USER:payflow}
    password: ${POSTGRES_PASSWORD:payflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: payflow

application:
  jwt:
    secret: ${JWT_SECRET:Q00qVqgM+A1zSb7FBfSGx6vzK9sUZhpxP5aBzWlLvp0=}
    expiration: ${JWT_EXPIRATION:86400000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

payflow:
  service:
    urls:
      order: ${ORDER_SERVICE_URL:http://localhost:8082}
      payment: ${PAYMENT_SERVICE_URL:http://localhost:8083}

resilience4j:
  ratelimiter:
    instances:
      login:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 10s
      register:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 30s
      refresh:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 5s