spring:
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: payflow

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082