spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: ${DB_PASSWORD:devpassword}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379
