server:
  port: 8081
spring:
  application:
    name: payment-service
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:postgres}
  sql:
    init:
      mode: always
  profiles:
    default: local
management:
  endpoints:
    web:
      exposure:
        include: health,info
