spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_db}
    username: ${DB_USERNAME:payflow}
    password: ${DB_PASSWORD:payflow}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:devpassword}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:YEh9YrZWacfeeM0F3PjuvPxvVuuB6ZCn2p7bsjcdBHY}
  simulator:
    base-url: ${SIMULATOR_SERVICE_URL:http://localhost:8086}
  webhook:
    service-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
  order:
    service-url: ${ORDER_SERVICE_URL:http://localhost:8082}
  auth:
    service-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  gateway-trust:
    enabled: false
