spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: payflow
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379
      password: devpassword

application:
  kafka:
    topic:
      payment-events: payment.events
      webhook-updates: webhook.updates
      order-events: order.events
      payment-status-updates: payment.status.updates
      payment-events-dlt: payment.events.dlt
      payment-status-updated: payment.status.updated
  simulator:
    base-url: http://localhost:8086
  webhook:
    service-url: http://localhost:8085
  order:
    service-url: http://localhost:8082
  auth:
    service-url: http://localhost:8081
  gateway-trust:
    enabled: false
  security:
    jwt:
      secret-key: swvCyTYU5b02Np0Eq8u9dkjXGGzlHkiERfJVJqFDZ0U=
      expiration-seconds: 86400
      refresh-expiration-seconds: 604800