spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

application:
  simulator:
    base-url: ${SIMULATOR_SERVICE_URL}
  ledger:
    base-url: ${LEDGER_SERVICE_URL}
  payment:
    checkout-base-url: ${CHECKOUT_BASE_URL}
