spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paymentdb
    username: payment
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:pg-dev-password}}

  kafka:
    bootstrap-servers: kafka:29092

application:
  simulator:
    base-url: ${SIMULATOR_BASE_URL:http://simulator-service:8086}
  webhook:
    service-url: ${WEBHOOK_SERVICE_URL:http://webhook-service:8085}
  order:
    service-url: ${ORDER_SERVICE_URL:http://order-service:8082}
  auth:
    service-url: ${AUTH_SERVICE_URL:http://auth-service:8081}

  gateway-trust:
    enabled: true

logging:
  level:
    root: INFO
