spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:payment_gateway}
    username: payment
    password: ${DB_PASSWORD:devpassword}
    driver-class-name: org.mariadb.jdbc.Driver

  kafka:
    bootstrap-servers: kafka:29092

application:
  simulator:
    base-url: lb://simulator-service
  webhook:
    service-url: lb://notification-service
  order:
    service-url: lb://order-service
  auth:
    service-url: lb://auth-service

  gateway-trust:
    enabled: true

logging:
  level:
    root: INFO