server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application:
    name: order-service

# PayFlow Centralized Configuration
payflow:
  database:
    enabled: true
    name: payflow_order
  kafka:
    enabled: true
  service:
    urls:
      payment: ${PAYMENT_SERVICE_URL:http://payment-service:8083}
      notification: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:ZGV2LW9ubHktand0LXNlY3JldC1jaGFuZ2UtbWUtcGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9uLTIwMjYtcGF5Zmxvdw==}
      expiration-seconds: 3600
      refresh-expiration-seconds: 2592000
  kafka:
    topic:
      order-events: order.events
      order-events-dlt: order.events.dlt
      payment-events: payment.events
      notification-events: notification.events

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG