package dev.payment.common.saga;

public enum SagaStatus {
    STARTED,
    RISK_CHECK_IN_PROGRESS,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    SETTLEMENT_IN_PROGRESS,
    SETTLEMENT_COMPLETED,
    REFUND_IN_PROGRESS,
    REFUND_COMPLETED,
    CANCELLED,
    COMPENSATING
}
