spring:
  config:
    import: vault://secret/order-service

vault:
  enabled: true
  token: ${VAULT_TOKEN:}

datasource:
  password: ${DB_PASSWORD:${vault:db-password:}}

application:
  payment-service:
    url: ${PAYMENT_SERVICE_URL:http://payment-service:8083}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

logging:
  level:
    root: INFO
    dev.payment: INFO
    org.springframework.security: INFO
