spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_order
    username: ${DB_USERNAME:payflow}
    password: ${DB_PASSWORD:payflow}
  kafka:
    bootstrap-servers: localhost:9092

application:
  payment-service:
    url: http://localhost:8083
  notification-service:
    url: http://localhost:8084

server:
  port: 8082

logging:
  level:
    root: INFO
    dev.payment.orderservice: DEBUG
