server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: payflow
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092

application:
  payment-service:
    url: http://localhost:8083
  notification-service:
    url: http://localhost:8085

logging:
  level:
    root: INFO
    dev.payment: DEBUG