#!/bin/bash

echo "=========================================="
echo "Jenkins Setup - Simple Version"
echo "=========================================="
echo ""
echo "Go to: http://localhost:8080"
echo "Login: admin / Admin@12345"
echo ""
echo "1. Create Job: payment-gateway"
echo "   - Type: Pipeline"
echo "   - Parameter: ENVIRONMENT (dev, staging, prod)"
echo "   - Script Path: jenkins/Jenkinsfile"
echo ""
echo "2. Add ONE credential:"
echo "   - ID: ghcr-token"
echo "   - Secret: your-github-token"
echo ""
echo "3. For staging/prod, set these as SYSTEM ENVIRONMENT VARIABLES on the server:"
echo "   - VAULT_TOKEN=<vault-token>"
echo "   - VAULT_ADDR=https://vault.yourdomain.com:8200"
echo ""
echo "That's it!"
