#!/bin/bash

JENKINS_URL="http://localhost:8080"
JOB_NAME="payment-gateway"

echo "Creating Jenkins job..."
echo ""
echo "Please do the following manually:"
echo ""
echo "1. Go to: $JENKINS_URL"
echo "2. Login with: admin / Admin@12345"
echo "3. Click 'New Item'"
echo "4. Enter name: $JOB_NAME"
echo "5. Select 'Pipeline'"
echo "6. Check 'Git' under 'Lightweight checkout'"
echo "7. Under 'Pipeline', select 'Pipeline script from SCM'"
echo "   - SCM: Git"
echo "   - Repository: /Users/macbookair/Documents/GitHub/payment-gateway"
echo "   - Script Path: jenkins/Jenkinsfile"
echo "8. Save"
echo ""
echo "Then add credentials:"
echo "1. Go to: $JENKINS_URL/credentials/store/system"
echo "2. Add Credentials (kind: Secret text):"
echo "   - ID: db-password, Secret: payment_dev_pass"
echo "   - ID: redis-password, Secret: redis_dev_pass"
echo "   - ID: jwt-secret, Secret: cHJvZHVjdGlvbi1wYXltZW50LWdhdGV3YXkta2V5LXYxMjM0NTY3ODkw"
echo ""
echo "Run build with:"
echo "curl -X POST -u admin:Admin@12345 $JENKINS_URL/job/$JOB_NAME/build"
