services:
  payment:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8084}
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
  ledger:
    url: ${LEDGER_SERVICE_URL:http://localhost:8082}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
  risk:
    url: ${RISK_SERVICE_URL:http://localhost:8085}
  settlement:
    url: ${SETTLEMENT_SERVICE_URL:http://localhost:8086}
  simulator:
    url: ${SIMULATOR_SERVICE_URL:http://localhost:8087}
