server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379

  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader

      routes:
        - id: payment-auth
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/auth/**

        - id: payment-orders
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-transactions
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/payments/**,/api/v1/admin/**

        - id: payment-webhooks
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/webhooks/**

        - id: payment-docs
          uri: http://payment-service:8084
          predicates:
            - Path=/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**

        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/platform/auth/**
          filters:
            - RewritePath=/platform/auth/(?<segment>.*), /internal/platform/${segment}

        - id: ledger-service
          uri: http://ledger-service:8082
          predicates:
            - Path=/platform/ledger/**
          filters:
            - RewritePath=/platform/ledger/(?<segment>.*), /internal/platform/${segment}

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/platform/notification/**
          filters:
            - RewritePath=/platform/notification/(?<segment>.*), /internal/platform/${segment}

        - id: risk-service
          uri: http://risk-service:8085
          predicates:
            - Path=/platform/risk/**
          filters:
            - RewritePath=/platform/risk/(?<segment>.*), /internal/platform/${segment}

        - id: settlement-service
          uri: http://settlement-service:8086
          predicates:
            - Path=/platform/settlement/**
          filters:
            - RewritePath=/platform/settlement/(?<segment>.*), /internal/platform/${segment}

        - id: simulator-service
          uri: http://simulator-service:8087
          predicates:
            - Path=/platform/simulator/**
          filters:
            - RewritePath=/platform/simulator/(?<segment>.*), /internal/platform/${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO

application:
  gateway:
    internal-secret: q8V3YkT9Z3xkY2FhZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=

security:
  jwt:
    secret-key: q8V3YkT9Z3xkY2FhZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=