spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
      password: devpassword

application:
  services:
    auth: http://localhost:8081
    order: http://localhost:8084
    payment: http://localhost:8083
    notification: http://localhost:8085
    webhook: http://localhost:8085
    simulator: http://localhost:8086
    analytics: http://localhost:8089
