services:
  payment:
    url: ${PAYMENT_SERVICE_URL}
  auth:
    url: ${AUTH_SERVICE_URL}
  ledger:
    url: ${LEDGER_SERVICE_URL}
  notification:
    url: ${NOTIFICATION_SERVICE_URL}
  risk:
    url: ${RISK_SERVICE_URL}
  settlement:
    url: ${SETTLEMENT_SERVICE_URL}
  simulator:
    url: ${SIMULATOR_SERVICE_URL}
