server:
  port: ${SERVER_PORT:8089}

spring:
  application:
    name: analytics-service

payflow:
  database:
    name: payflow_analytics

application:
  kafka:
    topic:
      payment-events: payment.events
      order-events: order.events
  analytics:
    batch-size: 100
    window-size: PT1H