server:
  port: 8089

spring:
  application:
    name: analytics-service
  profiles:
    active: docker

payflow:
  database:
    name: payflow_analytics

application:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
