server:
  port: ${SERVER_PORT:8089}

spring:
  application:
    name: analytics-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

payflow:
  database:
    name: payflow_analytics

application:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic:
      payment-events: payment.events
      order-events: order.events
  analytics:
    batch-size: 100
    window-size: PT1H