{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ $root.Values.global.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ $root.Values.global.namespace }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ $root.Values.postgresql.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ $root.Values.postgresql.auth.username }}
        - name: POSTGRES_PASSWORD
          value: {{ $root.Values.postgresql.auth.password }}
        - name: POSTGRES_DB
          value: {{ $root.Values.postgresql.auth.database }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: {{ $root.Values.postgresql.resources.requests.cpu }}
            memory: {{ $root.Values.postgresql.resources.requests.memory }}
          limits:
            cpu: {{ $root.Values.postgresql.resources.limits.cpu }}
            memory: {{ $root.Values.postgresql.resources.limits.memory }}
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ $root.Values.postgresql.primary.persistence.size }}