CREATE TABLE ledger_accounts
(
    id UUID PRIMARY KEY,
    account_code VARCHAR(64) NOT NULL UNIQUE,
    account_name VARCHAR(120) NOT NULL,
    type VARCHAR(32) NOT NULL,
    balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE journal_entries
(
    id UUID PRIMARY KEY,
    reference VARCHAR(64) NOT NULL,
    debit_account_code VARCHAR(64) NOT NULL,
    credit_account_code VARCHAR(64) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    narration VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
