spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_notification
  data:
    redis:
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

application:
  payment-service:
    url: http://localhost:8083