server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/paymentdb?currentSchema=notification_core}
    username: ${DB_USERNAME:payment}
    password: ${DB_PASSWORD:paymentpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    create-schemas: true
    schemas: notification_core
    default-schema: notification_core

management:
  endpoints:
    web:
      exposure:
        include: health,info
