server:
  port: ${APP_PORT:8084}

spring:
  application:
    name: merchant-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payflow}
    username: ${POSTGRES_USER:payflow}
    password: ${POSTGRES_PASSWORD:payflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: merchant_schema
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

services:
  payment-service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8083}
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html